rm(list = ls())
'
This script plots the bias-variance tradeoff and the MSE of the boosted smoothing spline 
and a cubic smoothing spline with varying boosting iterations and degrees of freedom respectively.

Sources: Data is generated by the following scripts
toy_boosting_iterations_bias_variance: bias/variance of boosted ss
toy_boosting_iterations: mse of boosted ss
toy_cs_spline_bias_variance: bias/variance of cubic ss
toy_cs_spline_df: mse of cubic ss
'

boost_variance_bias <- readRDS(file = "../99_Stored_Data/toy_boosting_iterations_bias_variance.rds")
boost_mse <- readRDS(file = "../99_Stored_Data/toy_boosting_iterations_mse.rds")

spline_variance_bias <- readRDS(file = "../99_Stored_Data/toy_cs_spline_bias_variance.rds")
spline_mse <- readRDS(file = "../99_Stored_Data/toy_cs_spline_df_mse.rds")

n_boost <- 200
n_df <- 40

pdf('../../06_Plots/Boosting_Theory/toy_mse_bv_plot.pdf', width = 6, height=4)
par(mfrow = c(1,2))
plot(seq(n_boost), boost_mse, type = "l", ylim = c(0,0.8), xlab = "Boosting Iterations", ylab = "", main = "Boosting", lty = 2)
lines(seq(n_boost), boost_variance_bias[1,], lty = 1, col = "red")
lines(seq(n_boost), boost_variance_bias[2,], lty = 3)
legend("topleft", legend=c("MSE", "variance", "squared bias"), col=c("black", "red", "black"), lty=c(2,1,3), cex=0.75, y.intersp=0.5, bty='n')

plot(seq(n_df), spline_mse, type = "l", ylim = c(0,0.8), xlab = "Degrees of Freedom", ylab = "", main = "Cubic Smoothing Spline", lty = 2)
lines(seq(n_df), spline_variance_bias[1,], lty = 1, col = "red")
lines(seq(n_df), spline_variance_bias[2,], lty = 3)
dev.off()


#### GGPLOT2 Implementation ------
library(ggplot2)
library(gridExtra)
library(ggpubr)

pl1 <- ggplot(data.frame(x=seq(n_boost), MSE = boost_mse, Variance = boost_variance_bias[1,], Bias = boost_variance_bias[2,]))+
  geom_line(aes(x=x, MSE, linetype = "MSE"))+
  geom_line(aes(x=x, Variance, linetype = "Variance"))+
  geom_line(aes(x=x, Bias, linetype = "Squared Bias"))+
  ylim(0, 0.8)+
  xlab("Boosting iterations")+
  ylab("")+
  ggtitle("Boosting")+
  theme_bw()+
  theme(panel.grid = element_blank())+
  scale_linetype_manual(name = "", 
                        values=c(3,1,2), labels=c("MSE","Squared Bias", "Variance"))
    
pl2 <- ggplot(data.frame(x=seq(n_df), MSE = spline_mse, Variance = spline_variance_bias[1,], Bias = spline_variance_bias[2,]), aes(x=x))+
  geom_line(aes(y = MSE, linetype = "MSE"))+
  geom_line(aes(y=Variance, linetype = "Variance"))+
  geom_line(aes(y=Bias, linetype = "Squared Bias"))+
  ylim(0, 0.8)+
  xlab("Degrees of freedom")+
  ylab("")+
  ggtitle("Cubic Smoothing Spline")+
  theme_bw()+
  theme(panel.grid = element_blank())+
  scale_linetype_manual(name = "", 
                        values=c(3,1,2), labels=c("MSE","Squared Bias", "Variance"))

combined_plot <- ggarrange(pl1, pl2, ncol=2, nrow=1, common.legend = TRUE, legend="bottom")
# grid.arrange(pl1, pl2, ncol = 2)
ggsave(combined_plot, file = '../../06_Plots/Boosting_Theory/toy_mse_bv_plot.pdf', width = 6, height = 4)
