rm(list =ls())

library(tikzDevice)

'
This script plots the bias-variance tradeoff and the MSE of the model (4.2) in Bühlmann/Yu 
with varying numbers of boosting iterations.

Sources: Data is generated by the following scripts
42_boost_iter_bias_variance: bias/variance/mse of boosted model
'

n_boost <- 300 #250

boost_variance_bias_mse <- readRDS(file = "../99_Stored_Data/42_boost_iter_bias_variance.rds")

### MSE decomposition
tikz('../../06_Plots/Main_Simulation/42_boost_iter_mse_decomp.tex', width = 6, height=4)
plot(seq(n_boost), boost_variance_bias_mse[3,1:300], 
     type = "l", 
     ylim = c(0,5),
     xlab = "Boosting iterations",
     ylab = "",
     main = "Uncorrelated Design - MSE Decomposition")
lines(seq(n_boost), boost_variance_bias_mse[1,1:300], lty = 2)
lines(seq(n_boost), boost_variance_bias_mse[2,1:300], lty = 3)
dev.off()

### comparison l2boost (development and aic) vs lasso
tikz('../../06_Plots/Main_Simulation/model42_boost_iter.tex', width = 6, height=4)
plot(seq(n_boost), boost_variance_bias_mse[3,1:300], 
     type = "l", 
     ylim = c(2,6),
     xlab = "Boosting iterations",
     ylab = "MSE",
     main = "Uncorrelated Design")
abline(h=2.7864, lty = 2) #l2boost
abline(h=3.0026, lty = 3) #lasso
dev.off()


#### GGPLOT2 IMPLEMENTATION
library(ggplot2)
library(dplyr)
library(gridExtra)

df <- data.frame(x = seq(n_boost), MSE = boost_variance_bias_mse[3,1:300], variance = boost_variance_bias_mse[1,1:300], bias = boost_variance_bias_mse[2,1:300])
df_plot <- df %>% 
  ggplot()+
  geom_line(aes(x=x, y= MSE, linetype = "MSE"))+
  geom_line(aes(x=x, y= variance, linetype = "Variance"))+
  geom_line(aes(x=x, y= bias, linetype = "Squared Bias"))+
  xlab("Boosting iterations")+
  ylim(0,5)+
  ggtitle("Uncorrelated Design - MSE Decomposition")+
  theme_bw()+
  theme(panel.grid = element_blank(), legend.position = "bottom")+
  scale_linetype_manual(name = "", 
                        values=c(1,3,2), labels=c("MSE","Squared Bias", "Variance"))
ggsave(df_plot, file = '../../06_Plots/Main_Simulation/42_boost_iter_mse_decomp.pdf', width = 6, height = 4)
  