rm(list =ls())

'
This script plots the bias-variance tradeoff and the MSE of the model (4.3) in Bühlmann/Yu 
with varying numbers of boosting iterations.

Sources: Data is generated by the following scripts
43_boost_iter_bias_variance: bias/variance of boosted model
'

n_boost <- 300 #250

boost_variance_bias_mse <- readRDS(file = "../99_Stored_Data/43_boost_iter_bias_variance.rds")

#### MSE decomposition
pdf('../../06_Plots/Main_Simulation/43_boost_iter_mse_decomp.pdf', width = 6, height = 4)
plot(seq(n_boost), boost_variance_bias_mse[3,1:300], 
     type = "l", 
     ylim = c(0,5),
     xlab = "Boosting iterations",
     ylab = "",
     main = "Correlated Design - MSE Development")
dev.off()

### comparison l2boost (development & aic) vs lasso
png('../../06_Plots/Main_Simulation/model43_boost_iter.png', res=600, height=10, width=10, units="in")
plot(seq(n_boost), boost_variance_bias_mse[3,1:300], 
     type = "l", 
     ylim = c(1,6),
     xlab = "Boosting iterations",
     ylab = "MSE",
     main = "Correlated Design")
abline(h=1.4853, lty = 2) #l2boost
abline(h=1.7796, lty = 3) #lasso
dev.off()




#### GGPLOT2 IMPLEMENTATION
library(ggplot2)
library(dplyr)
library(gridExtra)

df <- data.frame(x = seq(150), MSE = boost_variance_bias_mse[3,1:150], variance = boost_variance_bias_mse[1,1:150], bias = boost_variance_bias_mse[2,1:150])
df_plot <- df %>% 
  ggplot()+
  geom_line(aes(x=x, y= MSE))+
  xlab("Boosting iterations")+
  ylim(0,5)+
  ggtitle("Correlated Design - MSE Development")+
  theme_bw()+
  theme(panel.grid = element_blank(), legend.position = "none")
ggsave(df_plot, file = '../../06_Plots/Main_Simulation/43_boost_iter_mse_decomp.pdf', width = 6, height = 4)
